# Chapter 11: Numerics and Numpy

<div id="toc"></div>

## 11-1. Creating Arrays
* Problem  
* Solution  
* How It Works  

In [1]:
import numpy as np
list1 = [1, 2, 3.0, 4]

In [2]:
array1 = np.array(list1)
array1

array([ 1.,  2.,  3.,  4.])

In [3]:
complex1 = np.array(list1, dtype=complex)
complex1

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j])

In [4]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix1

array([[1, 2],
       [3, 4]])

In [5]:
empty1 = np.empty([2, 2], dtype=int)
empty1

array([[0, 0],
       [0, 0]])

In [6]:
zero1 = np.zeros((2, 3), dtype=float)
zero1

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [7]:
ones1 = np.ones((3, 2), dtype=int)
ones1

array([[1, 1],
       [1, 1],
       [1, 1]])

## 11-2. Copying an Array
* Problem  
* Solution  
* How It Works  

In [8]:
a = np.ones((6,), dtype=int)
a

array([1, 1, 1, 1, 1, 1])

In [9]:
b = a

In [10]:
view1 = ones1.view()
# Do these variables point to the same object?
view1 is ones1

False

In [12]:
view1.base is ones1

True

In [13]:
view1.shape = 2,3
ones1

array([[1, 1],
       [1, 1],
       [1, 1]])

In [14]:
view1

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
copy1 = a.copy()
a is copy1

False

In [16]:
a is copy1.base

False

## 11-3. Accessing Array Data
* Problem  
* Solution  
* How It Works  

In [17]:
a[1] = 2
a

array([1, 2, 1, 1, 1, 1])

In [18]:
a[1:3]

array([2, 1])

In [19]:
ones1[1, 1] = 2
ones1

array([[1, 1],
       [1, 2],
       [1, 1]])

In [20]:
ones1[1, : ]

array([1, 2])

## 11-4. Manipulating a Matrix
* Problem  
* Solution  
* How It Works  

In [21]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [22]:
np.linalg.norm(a)

5.4772255750516612

In [23]:
a.trace()

5.0

In [25]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

## 11-5. Calculating Fast Fourier Transforms
* Problem  
* Solution  
* How It Works  

In [ ]:
# a is a 1-dimensional array
np.fft.fft(a)
# b is a 2-dimensional array
np.fft.fft2(b)
# c is a 3-dimensional array
np.fft.fftn(c)

In [ ]:
np.fft.fft(c, axis=1)

## 11-6. Loading File Data into an Array
* Problem  
* Solution  
* How It Works  

In [ ]:
txt1 = np.loadtxt('mydata.txt')

In [ ]:
txt2 = np.loadtxt('mydata.txt', delimiter=',')

In [ ]:
data = np.load('mydata.npy')

## 11-7. Saving Arrays
* Problem  
* Solution  
* How It Works  

In [ ]:
np.save('mydata.npy', data)

In [ ]:
np.savetxt('mydata.csv', data, delimiter=',')

## 11-8. Generating Random Numbers
* Problem  
* Solution  
* How It Works  

In [ ]:
rand1 = np.random.geometric(p=0.5)

In [ ]:
np.random.seed(42)

In [ ]:
rand2 = np.random.random()

## 11-9. Calculating Basic Statistics
* Problem  
* Solution  
* How It Works  

In [ ]:
a = np.array([1, 2, 3, 4, 5])
np.mean(a)

In [ ]:
np.median(a)

In [ ]:
np.var(a)

In [ ]:
np.std(a)

## 11-10. Computing Histograms
* Problem  
* Solution  
* How It Works 

In [28]:
b = np.array([1,2,1,2,3,1,2,3,3,2,1])
np.histogram(b)

(array([4, 0, 0, 0, 0, 4, 0, 0, 0, 3], dtype=int64),
 array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ]))

In [29]:
np.histogram(b, 3)

(array([4, 4, 3], dtype=int64),
 array([ 1.        ,  1.66666667,  2.33333333,  3.        ]))